"""empty message

Revision ID: 35cdbdd25d05
Revises: None
Create Date: 2015-06-05 21:17:21.305210

"""

# revision identifiers, used by Alembic.
revision = '35cdbdd25d05'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mt_extend_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('mtannouncements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('publisher', sa.String(length=32), nullable=True),
    sa.Column('publish_date', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mtscaleresults',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('setup_time', sa.DateTime(), nullable=True),
    sa.Column('finished_time', sa.DateTime(), nullable=True),
    sa.Column('result_content', sa.Text(), nullable=True),
    sa.Column('result_score', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('scale_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mtscales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('scale_introductions', sa.Text(), nullable=True),
    sa.Column('scale_content', sa.PickleType(), nullable=True),
    sa.Column('scale_algorithm', sa.PickleType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mtunfinishedscales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('setup_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('started', sa.Boolean(), nullable=True),
    sa.Column('answer_content', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('scale_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mtuserextendinfos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('extend_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mtusers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('sex', sa.String(length=16), nullable=True),
    sa.Column('nation', sa.String(length=16), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('blood_type', sa.String(length=16), nullable=True),
    sa.Column('health', sa.String(length=64), nullable=True),
    sa.Column('commit', sa.Text(), nullable=True),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mtusers')
    op.drop_table('mtuserextendinfos')
    op.drop_table('mtunfinishedscales')
    op.drop_table('mtscales')
    op.drop_table('mtscaleresults')
    op.drop_table('mtannouncements')
    op.drop_table('mt_extend_fields')
    ### end Alembic commands ###
